// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PassportsRehaulReact.Data;

#nullable disable

namespace PassportsRehaulReact.Migrations
{
    [DbContext(typeof(PassportDbContext))]
    [Migration("20230504201936_Add_PassPortLockBoxes_Table")]
    partial class Add_PassPortLockBoxes_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PassportsRehaulReact.Models.Employees", b =>
                {
                    b.Property<string>("cityCell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cityphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idnum")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PassportsRehaulReact.Models.PassPortARSCG", b =>
                {
                    b.Property<int>("PPARSIDCG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PPARSIDCG"), 1L, 1);

                    b.Property<string>("ARSDescription")
                        .IsRequired()
                        .HasColumnType("nchar");

                    b.Property<decimal>("ARSFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.HasKey("PPARSIDCG");

                    b.ToTable("PassPortARSCGs");
                });

            modelBuilder.Entity("PassportsRehaulReact.Models.PassPortARSSD", b =>
                {
                    b.Property<int>("PPARSIDSD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PPARSIDSD"), 1L, 1);

                    b.Property<string>("ARSDescription")
                        .IsRequired()
                        .HasColumnType("nchar");

                    b.Property<decimal>("ARSFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.HasKey("PPARSIDSD");

                    b.ToTable("PassPortARSSDs");
                });

            modelBuilder.Entity("PassportsRehaulReact.Models.PassPortFees", b =>
                {
                    b.Property<int>("PPFEEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PPFEEID"), 1L, 1);

                    b.Property<decimal>("FeeAmtCG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FeeAmtSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FeeDescription")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.HasKey("PPFEEID");

                    b.ToTable("PassPortFeess");
                });

            modelBuilder.Entity("PassportsRehaulReact.Models.PassPortLockBoxes", b =>
                {
                    b.Property<int>("LOCKBOXID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LOCKBOXID"), 1L, 1);

                    b.Property<string>("LBoxDescription")
                        .IsRequired()
                        .HasColumnType("char(50)");

                    b.HasKey("LOCKBOXID");

                    b.ToTable("PassPortLockBoxess");
                });
#pragma warning restore 612, 618
        }
    }
}
